# Generated by Django 5.0.6 on 2024-07-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('R', 'recarga'), ('T', 'transferencia'), ('RE', 'retiro'), ('P', 'pago')], max_length=2)),
            ],
            options={
                'db_table': 'typeTransaction',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('curp', models.TextField(max_length=255, null=True)),
                ('email', models.TextField(max_length=55)),
                ('name', models.TextField(max_length=255)),
                ('surnames', models.TextField(max_length=255, null=True)),
                ('password', models.TextField(max_length=255)),
                ('ine', models.TextField(max_length=255, null=True)),
                ('photo', models.TextField(max_length=255, null=True)),
                ('stripe', models.TextField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.roles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.users')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('status', models.TextField(choices=[('E', 'error'), ('X', 'exitoso'), ('P', 'en proceso')], default='P', max_length=2)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.typetransaction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id', to='pagos.users')),
                ('user_trans_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_transferencia', to='pagos.users')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.users')),
            ],
            options={
                'db_table': 'qr',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('last_day', models.DateField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.users')),
            ],
            options={
                'db_table': 'balance',
            },
        ),
    ]
