# Generated by Django 5.0.6 on 2024-08-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
