# Generated by Django 5.0.6 on 2024-08-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_users_is_validate_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_validate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
