# Generated by Django 5.0.6 on 2024-08-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_users_is_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(max_length=55, unique=True),
        ),
    ]
